[package]
name = "ic_siwe_provider"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9.11"
ic-cdk = "0.11.3"
ic_siwe = { path = "../ic_siwe" }
serde = "1.0.193"
serde_json = "1.0.108"
ic-stable-structures = "0.6.0"
serde_bytes = "0.11"

[dev-dependencies]
pocket-ic = "2.0.1"
siwe = "0.6"
hex = "0.4.3"
ethers = "2.0.10"
rand = "0.8.4"

