[package]
name = "ic_siwe_provider"
version = "0.0.6"
edition = "2021"
authors = ["Kristofer Lund <kristofer@kristoferlund.se>"]
description = "Using the pre built ic_siwe_provider canister is the easiest way to integrate Ethereum wallet authentication into an Internet Computer (ICP) application."
license = "MIT"
homepage = "https://github.com/kristoferlund/ic-siwe"
repository = "https://github.com/kristoferlund/ic-siwe"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.9"
ic-cdk = "0.15.0"
ic_siwe = { path = "../ic_siwe" }
ic-stable-structures = "0.6.5"
ic-certified-map = "0.4.0"
serde = "1.0.193"
serde_json = "1.0.108"
serde_bytes = "0.11"

[dev-dependencies]
ethers = "2.0.10"
hex = "0.4.3"
ic-agent = "0.36.0"
pocket-ic = "3.1.0"
siwe = "0.6"
rand = "0.8.4"
ring = "0.17.7"
